services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  task-service:
    build:
      context: ./task-service
    container_name: task-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8002:8002"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}